### ISSUE TITLE
direct volume (nfs)

### ISSUE THREAD

**Issue by ondrejsika** [ondrejsika/kubernetes-training#167]
```
      volumes:
        - name: data
          nfs:
            path: /nfs
            server: 167.172.190.200
```
