### ISSUE TITLE
add init container example with wait for job

### ISSUE THREAD

**Issue by ondrejsika** [ondrejsika/kubernetes-training#184]
```
        - name: wait-for-migrations
          image: sikalabs/kubectl
          args:
            - /bin/sh
            - -c
            - "kubectl wait --for=condition=complete --timeout=600s job/sleep20s"
```
